### PR TITLE
Implement post crud

### PR DESCRIPTION
**Pull request by oesukam**
#### What does this PR do?
Implement post crud

### CODE REVIEW

**Comment by oesukam** [comment]
[Users should be able to add their profiles](https://trello.com/c/6AYTuloT/6-users-should-be-able-to-add-their-profiles)

**Comment by oesukam** [comment]
[Users should be able to add their profiles](https://trello.com/c/6AYTuloT/6-users-should-be-able-to-add-their-profiles)

**Comment by oesukam** [comment]
[Users should be able to create a post.](https://trello.com/c/SertiHNW/8-users-should-be-able-to-create-a-post)

**Review by gracelungu — APPROVED** [review]
Good job! @oesukam, We should just make sure to add a Tag schema in order to auto-suggest these to users when creating a post.

**Pull request merged**
